# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89742816f58845a0c24e5164601e784a8c79fe3d59de1cbb378378399cd4d9412fb4659008f1cbdc3a06578cdffba83770284fdb556549fad8834e0ea227f54c

test:
  secret_key_base: ccc9de0c3d630d078854060d9e69615d0d53b96e440608fdaa71fcac3cfffa0939fb3c40df192956257dab63fdabb97746094d27e072c859d25c85f1e58cbfec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
